#!/bin/bash
jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git
git config --global user.name "Ramesh Doraiswamy
git config --global user.email rdoraiswamy@gmail.com
